name: GH Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Install apt dependencies
        run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant
    
      - name: Intall Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install mkdocs-material and dependancies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin "mkdocs-material[imaging]"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Checkout
        uses: actions/configure-pages@v5.0.0

      - name: Build Site
        run: mkdocs gh-deploy --force
      
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./site
      
  deploy:
    environment:
      name: github-pages
      url: "https://blog.timewelltech.ca/"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.5
